sudo: required

language: bash

env:
  global:
    #- KIEKER_GIT="http://build.se.informatik.uni-kiel.de/gitlab/kieker/kieker.git"
    - KIEKER_GIT="https://github.com/dn3t-de/kieker.git"
  matrix:
    - DOCKER_IMAGE_TAG=openjdk6 GRADLE_TARGET="build" GRADLE_EXCLUDES="-x test"
    - DOCKER_IMAGE_TAG=openjdk7 GRADLE_TARGET="build" GRADLE_EXCLUDES="-x test"
    - DOCKER_IMAGE_TAG=openjdk8 GRADLE_TARGET="build" GRADLE_EXCLUDES="-x test"

branches:
  only:
    - master
    
services:
  - docker

before_install:
  - docker pull kieker/kieker-build:$DOCKER_IMAGE_TAG

script:
  - docker run kieker/kieker-build:$DOCKER_IMAGE_TAG /bin/bash -c "git clone ${KIEKER_GIT} kieker && cd kieker/ && ./gradlew ${GRADLE_TARGET} ${GRADLE_EXCLUDES}"
