sudo: required

language: bash

env:
  - DOCKER_IMAGE_TAG=openjdk6
  - DOCKER_IMAGE_TAG=openjdk7

branches:
  only:
    - master
    
services:
  - docker

before_install:
  - docker pull kieker/kieker-build:$DOCKER_IMAGE_TAG
  - docker run kieker/kieker-build:$DOCKER_IMAGE_TAG
  
script:
  - git clone ${KIEKER_GIT_REPO} kieker && \
  - ln -s /opt/kieker/build /opt/share/build && \
  - cd kieker/ && \
  - ./gradlew jenkinsBuild | tee /opt/share/kieker-build.log
