language: java
jdk: openjdk7

before_install:
  - gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - echo "deb https://cran.uni-muenster.de/bin/linux/ubuntu wily/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install r-base r-cran-rserve

gradle:
  - jenkinsBuild
  - jenkinsNightlyBuild