sudo: required

language: bash

env:
  - DOCKER_IMAGE_TAG=openjdk6
  - DOCKER_IMAGE_TAG=openjdk7

branches:
  only:
    - master
    
services:
  - docker

before_install:
  - docker pull kieker/kieker-build:$DOCKER_IMAGE_TAG
  - docker run -d kieker/kieker-build:$DOCKER_IMAGE_TAG
  - docker ps -a
